services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"  
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050 
    depends_on:
      - mongodb
      - backend  

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 for NGINX
    networks:
      - mern_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Absolute path for Windows Docker
    depends_on:
      - frontend
      - backend
      - mongodb

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
